/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Rene' at '10/7/16 11:51 AM' with Gradle 3.1
 *
 * @author Rene, @date 10/7/16 11:51 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
