/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Rene' at '10/5/16 8:13 AM' with Gradle 3.1
 *
 * @author Rene, @date 10/5/16 8:13 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
